### ISSUE TITLE
Using deprecated material-ui syntax 'theme.spacing.unit'

### ISSUE THREAD

**Issue by ryan-gray** [iamhosseindhv/notistack#169]
When using using enqueueSnackbar(), there is an error thrown in the console as show below. 
![Screen Shot 2019-09-23 at 4 10 48 PM](https://user-images.githubusercontent.com/25753632/65466751-fb6a2980-de1c-11e9-99e0-132e045cf1d8.png)

This should be updated to use theme.spacing(y) instead of theme.spacing.unit * y, as described in the error message

## Expected Behavior
No error is thrown from notistack when enqueuing a snackbar.

## Current Behavior
An error is thrown when enqueuing a snackbar related to deprecated usage of material-ui's spacing API.

## Steps to Reproduce
Link: https://codesandbox.io/s/notistack-simple-example-eo4ur?fontsize=14

1. Open developer tools
2. Click any of the buttons to add a snackbar 
3. Notice error in console

## Context
When material-ui removes this API, it could cause a breaking change for notistack.

## Your Environment

| Tech         | Version |
|--------------|---------|
| notistack                  | v0.9.1 |
| react                         | v16.9.0 |
| react-dom                | v16.9.0 |
| Chrome                    | v77 |
| @material-ui/core   | 4.4.3 |

**Comment by iamhosseindhv** [comment]
Thanks for reporting @ryan-gray. fix has been released

**Comment by ryan-gray** [comment]
Great, thank you!

**Comment by ryan-gray** [comment]
Which release is that? I only see 0.9.1.

**Comment by iamhosseindhv** [comment]
Its v0.9.2

**Comment by ryan-gray** [comment]
I'm still reproducing it in the code sandbox with 0.9.2:
https://codesandbox.io/s/notistack-simple-example-eo4ur?fontsize=14
